INSERT INTO categories (id, name)
VALUES (1, 'Electronics'),
       (2, 'Books'),
       (3, 'Home & Kitchen'),
       (4, 'Fashion'),
       (5, 'Sports & Outdoors'),
       (6, 'Beauty & Personal Care'),
       (7, 'Toys & Games'),
       (8, 'Office Supplies'),
       (9, 'Pet Supplies'),
       (10, 'Groceries');

INSERT INTO products (name, price, `description`, category_id)
VALUES ('Apple iPhone 15 128GB',
        29900.00,
        'A modern smartphone featuring a 6.1-inch Super Retina XDR display, A16 Bionic chip, dual-camera system, and 128GB storage. Suitable for everyday communication, photography, and mobile productivity.',
        1),
       ('Atomic Habits by James Clear',
        480.00,
        'A bestselling self-improvement book that explains how small daily habits can lead to remarkable long-term results. Popular among readers interested in productivity and personal growth.',
        2),
       ('Philips Air Fryer 4.1L',
        4580.00,
        'A compact air fryer designed for healthier cooking with less oil. Includes multiple cooking modes for fries, chicken, vegetables, and reheating leftovers.',
        3),
       ('Uniqlo Men Cotton Crew Neck T-Shirt',
        390.00,
        'A comfortable everyday short-sleeve cotton T-shirt with a simple crew neck design. Suitable for casual wear and layering.',
        4),
       ('Decathlon Yoga Mat 8mm',
        850.00,
        'A non-slip yoga mat with 8mm cushioning for comfort and stability during yoga, stretching, pilates, and home workouts.',
        5),
       ('CeraVe Moisturizing Cream 454g',
        650.00,
        'A dermatologist-recommended moisturizing cream formulated with ceramides and hyaluronic acid to help restore the skin barrier and provide long-lasting hydration.',
        6),
       ('LEGO Classic Medium Creative Brick Box',
        899.00,
        'A creative building set containing assorted LEGO bricks in various colors and shapes. Ideal for imaginative play and beginner construction projects for children.',
        7),
       ('Moleskine Classic Notebook Large',
        720.00,
        'A premium hardcover notebook with ruled pages, elastic closure, and ribbon bookmark. Commonly used for journaling, note-taking, and planning.',
        8),
       ('Pedigree Adult Dry Dog Food Beef Flavor 3kg',
        599.00,
        'A complete and balanced dry dog food made for adult dogs, providing essential nutrients, protein, and vitamins for daily health and energy.',
        9),
       ('Kirkland Signature Whole Almonds 1.36kg',
        459.00,
        'A large pack of whole roasted almonds suitable for snacking, baking, or adding to breakfast and salads. Popular for households seeking a convenient healthy snack option.',
        10);